### ISSUE TITLE
Nothing Happens

### ISSUE THREAD

**Issue by apippuM** [smokes/adobe-rpc#16]
I've already did all the steps, pywin32 installed in correct version, already installed all components in requirements.txt, but when i run the script, nothing happen. what's wrong?. I'm using python 3.8.2

**Comment by garrettsummerfi3ld** [comment]
Define "nothing happens" as I'm a little lost with your description.

Is there any log output in the console window?

**Comment by apippuM** [comment]
nvm, it's working now. nothing happen i mean, when i run the script and adobe app, the rich presence isn't showing in discord, the console keep showing "make sure pywin32 is installed, run adobe/discord app", but now i'm using python 3.6 and everything works just fine. sorry for my bad English tho
