### ISSUE TITLE
Premiere Pro not recognized

### ISSUE THREAD

**Issue by ghost** [smokes/adobe-rpc#2]
Premiere Pro not recognized

**Comment by smokes** [comment]
Which version ?

**Comment by ghost** [comment]
Premiere Pro CC 2019, v13.1

**Comment by NicholasBottone** [comment]
I cannot get this program to work with anything but Photoshop, when I run the script I get a message "Started Photoshop Rich Presence" followed by "Make sure Discord/Adobe app is running, retrying in 30 seconds..." even though I have Premiere Pro open.  I tried this with Premiere Pro 2018 v12.1.2, as well as with the last version of Premiere Pro 2019 (v13.1).
![See screenshot here.](https://user-images.githubusercontent.com/13754214/58376051-358af380-7f2f-11e9-8ad9-e4c25fd4f625.png)

**Comment by smokes** [comment]
Fixed by @phyzzz I think?
